### ISSUE TITLE
Vim 8.1 - E118: Too many arguments for function: go#def#Jump

### ISSUE THREAD

**Issue by Guitarbum722** [fatih/vim-go#2211]
### What did you do? (required. The issue will be **closed** when not provided.)
1. Placed cursor on a symbol, typed `gd` to move the cursor to the symbol's definition.
2. Message displayed `E118: Too many arguments for function: go#def#Jump`
3. No additional messages when used command `:messages` (same aforementioned message).

4. Used `git bisect` to point the problem to `8b4b0e3cea0f41aeb6810fbc30d57e4a639d1ee6`

### What did you expect to happen?
I would expect the cursor to be relocated to the definition of the symbol.

### What happened instead?
Error message from above description is displayed and the cursor did not move.

### Configuration (**MUST** fill this out):

* vim-go version:
`f040988`

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```let g:go_fmt_fail_silently = 0
let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"
let g:go_autodetect_gopath = 1
let g:go_highlight_space_tab_error = 0
let g:go_highlight_array_whitespace_error = 0
let g:go_highlight_trailing_whitespace_error = 0
let g:go_highlight_extra_types = 0
let g:go_highlight_operators = 0
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 0
let g:go_highlight_generate_tags = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_metalineter_enabled =         ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave =         1
let g:go_metalinter_deadline =         "5s"
let g:go_auto_type_info =              1
let g:go_def_mode = 'godef'```

* Vim version (first three lines from `:version`):
```VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 26 2019 01:54:18)
macOS version
Included patches: 1-1050```

* Go version (`go version`):
`go version go1.12.1 darwin/amd64`

* Go environment (`go env`):
```GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myname/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/myname/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kv/9jbf57tj6jz42vppvxk99pn40000gn/T/go-build286630394=/tmp/go-build -gno-record-gcc-switches -fno-common"```

**Comment by bhcleek** [comment]
I don't see any instances in vim-go of `go#def#Jump` that are missing an argument for the new parameter that was added to it in `8b4b0e3cea0f41aeb6810fbc30d57e4a639d1ee6`.

Are you using polyglot?

**Comment by Guitarbum722** [comment]
@bhcleek nope - not using polyglot.

**Comment by bhcleek** [comment]
`:verbose go#def#Jump`'s second line will output where the function was last defined. e.g.:
```
   function go#def#Jump(mode, type) abort
        Last set from ~/src/vim-go/autoload/go/def.vim line 8
```

Is yours last defined from where you vim-go installed?

**Comment by Guitarbum722** [comment]
All that is output is `E488: Trailing characters`

Is there something else I could try to extract the information you need?

I really appreciate the assistance by the way.

**Comment by bhcleek** [comment]
sorry, that should have been `:verbose function go#def#Jump`.

**Comment by Guitarbum722** [comment]
Aha!  It was defined in another `vim-go` installation under `~/.vim/pack/...`.  I removed that to use the `vim-go` installation under `~/.vim/bundle/...` and everything is great.

Thank you for this!

**Comment by FishinLab** [comment]
I met the same error
just like what you have done
```
grep go#def#Jump .vim/* -R | grep -v YouCompleteMe
mv .vim/bundle/vim-go/ftplugin /tmp/ 
```
error 118 is gone
@Guitarbum722 thanks for your issue
