### ISSUE TITLE
:GoInstall results in undefined: sort.Slice for go 1.8

### ISSUE THREAD

**Issue by cosminilie** [fatih/vim-go#1213]
### Behavior

When typing :GoInstall the application should compile and install in the gopath/bin, similar to the behaviour when running go install in a terminal.

The result however was that it failed due to the error: undefined: sort.Slice. 
The slice sort feature was added in go 1.8.

### Steps to reproduce:

1. Paste example in a main.go file:
https://play.golang.org/p/8PboMGmubj
2. Run :GoInstall
### Configuration

Add here your current configuration and additional information that might be
useful, such as:

*  OS - MacOS: sw_vers -productVersion
10.12.3
* vim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 16 2017 04:51:36)
MacOS X (unix) version
Included patches: 1-329
* go version: 1.8

I've also run :GoInstallBinaries to recompile binaries with go 1.8

**Comment by fatih** [comment]
Hi @cosminilie 

Thanks for the issue. There is nothing to do here as vim-go just uses the Go library. I assume you're setup is broken. It works fine with 1.8.
